# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create Release

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
        - SemanticKernel.Agents.Memory.Abstractions
        - SemanticKernel.Agents.Memory.Core
        # - SemanticKernel.Agents.Memory.MCP
        # - SemanticKernel.Agents.Memory.Plugin
        # - SemanticKernel.Agents.Memory.Service

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./

    - name: Extract numeric version
      id: extract_version
      run: |
        # Extract numeric version from tag (e.g., "0.0.1-beta02" -> "0.0.1.0")
        NUMERIC_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/-.*$//' | sed 's/$/\.0/')
        echo "numeric_version=$NUMERIC_VERSION" >> $GITHUB_OUTPUT
        echo "Full version: ${{ github.event.release.tag_name }}"
        echo "Numeric version: $NUMERIC_VERSION"

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ github.event.release.tag_name }} /p:PackageVersion=${{ github.event.release.tag_name }} /p:AssemblyVersion=${{ steps.extract_version.outputs.numeric_version }} /p:FileVersion=${{ steps.extract_version.outputs.numeric_version }}
      working-directory: ./

    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:Version=${{ github.event.release.tag_name }} /p:PackageVersion=${{ github.event.release.tag_name }}
      working-directory: ./

    - name: Push to GitHub Packages
      run: |
        dotnet nuget push **/${{ matrix.package }}.*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate
      working-directory: ./
